<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>BimOpenFlow.Nodes.TableOps</PackageId>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.DataFlowEngine.Abstractions\Ara3D.DataFlowEngine.Abstractions.csproj" />
    <ProjectReference Include="..\Ara3D.BimOpenSchema.DuckDb\Ara3D.BimOpenSchema.DuckDb.csproj" />
    <ProjectReference Include="..\BimOpenFlow.Nodes.Support\BimOpenFlow.Nodes.Support.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BimOpenFlow.Nodes.Support" />
    <Using Include="Ara3D.BimOpenSchema.DuckDb" />
  </ItemGroup>

</Project>
