<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>BimOpenFlow.Nodes.Tables</PackageId>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.DataFlowEngine.Abstractions\Ara3D.DataFlowEngine.Abstractions.csproj" />
    <ProjectReference Include="..\BimOpenFlow.Nodes.Support\BimOpenFlow.Nodes.Support.csproj" />
    <PackageReference Include="ClosedXML" Version="$(Ara3DClosedXmlVersion)" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="$(Ara3DMicrosoftDataSqliteVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BimOpenFlow.Nodes.Support" />
  </ItemGroup>

</Project>
