<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Ara3D.BimOpenSchema.IO</PackageId>
    <TargetFramework>net8.0</TargetFramework>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Reading and writing BIM Open Schema archives: Parquet tables in a zip.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.Logging" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Parquet.Net" Version="$(Ara3DParquetNetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\submodules\bim-open-schema\src\Ara3D.BimOpenSchema\Ara3D.BimOpenSchema.csproj" />
    <ProjectReference Include="..\Ara3D.BimOpenSchema.ObjectModel\Ara3D.BimOpenSchema.ObjectModel.csproj" />
  </ItemGroup>

</Project>
