<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.DataTable" Version="$(Ara3DSdkVersion)" />
    <ProjectReference Include="..\Ara3D.DataFlowEngine\Ara3D.DataFlowEngine.csproj" />
    <ProjectReference Include="..\Ara3D.NodeGraph\Ara3D.NodeGraph.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ara3D.DataFlowEngine.Runs.Tests" />
  </ItemGroup>

</Project>
