// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 8:55:17 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Capsule: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number Radius;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Capsule WithHeight(Number height) => new Capsule(height, Radius);
        [MethodImpl(AggressiveInlining)] public Capsule WithRadius(Number radius) => new Capsule(Height, radius);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Capsule(Number height, Number radius) { Height = height; Radius = radius; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Capsule Create(Number height, Number radius) => new Capsule(height, radius);

        // Static default implementation
        public static readonly Capsule Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Capsule self) => (self.Height, self.Radius);
        [MethodImpl(AggressiveInlining)] public static implicit operator Capsule((Number, Number) value) => new Capsule(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number radius) { height = Height; radius = Radius;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Capsule other) => Height.Equals(other.Height) && Radius.Equals(other.Radius);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Capsule other) => !(Height.Equals(other.Height) && Radius.Equals(other.Radius));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Capsule other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, Radius);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"Radius\" = {Radius} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 uv){
            var theta = uv.X.Turns;
            var h = this.Height.Multiply(((Number)0.5));
            var r = this.Radius;
            var v = uv.Y;
            var phiB = ((Number)0.5).Subtract(((Number)0.25).Multiply(v.Multiply(((Number)4)))).Turns;
            var phiT = ((Number)0.25).Subtract(((Number)0.25).Multiply(v.Subtract(((Number)0.75)).Multiply(((Number)4)))).Turns;
            return v.LessThanOrEquals(((Number)0.25)) ? (phiB.Sin.Multiply(theta.Cos).Multiply(r), phiB.Sin.Multiply(theta.Sin).Multiply(r), phiB.Cos.Multiply(r).Subtract(h)) : v.GreaterThanOrEquals(((Number)0.75)) ? (phiT.Sin.Multiply(theta.Cos).Multiply(r), phiT.Sin.Multiply(theta.Sin).Multiply(r), phiT.Cos.Multiply(r).Add(h)) : (theta.Cos.Multiply(r), theta.Sin.Multiply(r), v.Subtract(((Number)0.25)).Multiply(((Number)2)).Subtract(((Number)0.5)).Multiply(this.Height));
        }

public Boolean ClosedX { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 
public Boolean ClosedY { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class CapsuleExtensions
    {
    }
}
