// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 8:55:17 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Pyramid: ISolid
    {
        // Fields
        [DataMember] public readonly Number Height;
        [DataMember] public readonly Number BaseLength;

        // With functions 
        [MethodImpl(AggressiveInlining)] public Pyramid WithHeight(Number height) => new Pyramid(height, BaseLength);
        [MethodImpl(AggressiveInlining)] public Pyramid WithBaseLength(Number baseLength) => new Pyramid(Height, baseLength);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public Pyramid(Number height, Number baseLength) { Height = height; BaseLength = baseLength; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Pyramid Create(Number height, Number baseLength) => new Pyramid(height, baseLength);

        // Static default implementation
        public static readonly Pyramid Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Pyramid self) => (self.Height, self.BaseLength);
        [MethodImpl(AggressiveInlining)] public static implicit operator Pyramid((Number, Number) value) => new Pyramid(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number height, out Number baseLength) { height = Height; baseLength = BaseLength;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Pyramid other) => Height.Equals(other.Height) && BaseLength.Equals(other.BaseLength);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Pyramid other) => !(Height.Equals(other.Height) && BaseLength.Equals(other.BaseLength));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Pyramid other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Height, BaseLength);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Height\" = {Height}, \"BaseLength\" = {BaseLength} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Point3D Eval(Vector2 uv){
            var p = uv.X.SquarePoint.Multiply(this.BaseLength.Multiply(((Number)0.5)).Multiply(((Number)1).Subtract(uv.Y)));
            return (p.X, p.Y, uv.Y.Subtract(((Number)0.5)).Multiply(this.Height));
        }

public Boolean ClosedX { [MethodImpl(AggressiveInlining)] get  => ((Boolean)true); } 
public Boolean ClosedY { [MethodImpl(AggressiveInlining)] get  => ((Boolean)false); } 

        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class PyramidExtensions
    {
    }
}
