// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:44:52 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [DataContract, StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct ScalarField3D: IValue
    {
        // Fields
        [DataMember] public readonly System.Func<Vector3, Number> Function;

        // With functions 
        [MethodImpl(AggressiveInlining)] public ScalarField3D WithFunction(System.Func<Vector3, Number> function) => new ScalarField3D(function);

        // Regular Constructor
        [MethodImpl(AggressiveInlining)] public ScalarField3D(System.Func<Vector3, Number> function) { Function = function; }

        // Static factory function
        [MethodImpl(AggressiveInlining)] public static ScalarField3D Create(System.Func<Vector3, Number> function) => new ScalarField3D(function);

        // Static default implementation
        public static readonly ScalarField3D Default = default;

        // Implicit converters to/from single field
        [MethodImpl(AggressiveInlining)] public static implicit operator System.Func<Vector3, Number>(ScalarField3D self) => self.Function;
        [MethodImpl(AggressiveInlining)] public static implicit operator ScalarField3D(System.Func<Vector3, Number> value) => new ScalarField3D(value);

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(ScalarField3D other) => Function.Equals(other.Function);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(ScalarField3D other) => !(Function.Equals(other.Function));
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is ScalarField3D other ? Equals(other).Value : false;
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Intrinsics.CombineHashCodes(Function);
        [MethodImpl(AggressiveInlining)] public override string ToString() => $"{{ \"Function\" = {Function} }}";

        // Explicit implementation of interfaces by forwarding properties to fields

        // Implemented interface functions
        [MethodImpl(AggressiveInlining)] public Number Eval(Vector3 p) => this.Function(p);
[MethodImpl(AggressiveInlining)] public ScalarField3D Combine(ScalarField3D b, System.Func<Number, Number, Number> op){
            var _var41 = b;
            {
                var _var40 = this;
                {
                    var _var39 = op;
                    return new ScalarField3D((p)  => _var39.Invoke(_var40.Eval(p), _var41.Eval(p)));
                }
            }
        }

[MethodImpl(AggressiveInlining)] public ScalarField3D MapValue(System.Func<Number, Number> f){
            var _var43 = this;
            {
                var _var42 = f;
                return new ScalarField3D((p)  => _var42.Invoke(_var43.Eval(p)));
            }
        }

[MethodImpl(AggressiveInlining)] public ScalarField3D Union(ScalarField3D b) => this.Combine(b, (x, y)  => x.Min(y));
[MethodImpl(AggressiveInlining)] public ScalarField3D Intersection(ScalarField3D b) => this.Combine(b, (x, y)  => x.Max(y));
[MethodImpl(AggressiveInlining)] public ScalarField3D Difference(ScalarField3D b) => this.Combine(b, (x, y)  => x.Max(((Number)0).Subtract(y)));
[MethodImpl(AggressiveInlining)] public ScalarField3D Offset(Number amount){
            var _var44 = amount;
            return this.MapValue((x)  => x.Subtract(_var44));
        }


        // Unimplemented interface functions
    }
    // Extension methods for the type
    public static class ScalarField3DExtensions
    {
    }
}
