// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 8:55:17 PM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector2: IVector<Vector2>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector2 Create(Number x, Number y) => new Vector2(x, y);

        // Static default implementation
        public static readonly Vector2 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number)(Vector2 self) => (self.X, self.Y);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector2((Number, Number) value) => new Vector2(value.Item1, value.Item2);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number x, out Number y) { x = X; y = Y;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector2 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector2 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector2 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector2 a, Vector2 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector2 a, Vector2 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 2; }
        public IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X, Y); }
        [MethodImpl(AggressiveInlining)] public static Vector2 CreateFromComponents(IReadOnlyList<Number> numbers) => new Vector2(numbers[0], numbers[1]);

        [MethodImpl(AggressiveInlining)] public static Vector2 CreateFromComponent(Number x) => new Vector2(x, x);

        // Implemented interface functions
        public Point2D Point2D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Point2D(Vector2 x) => x.Point2D;
        public Ray2D Ray2D { [MethodImpl(AggressiveInlining)] get  => (Constants.Origin2D, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Ray2D(Vector2 v) => v.Ray2D;
        public Vector3 To3D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y, ((Integer)0)); } 
[MethodImpl(AggressiveInlining)] public Vector2 Add(Vector2 right) => this + right;
        [MethodImpl(AggressiveInlining)] public Vector2 Subtract(Vector2 right) => this - right;
        [MethodImpl(AggressiveInlining)] public Vector2 Multiply(Vector2 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector2 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)] public Vector2 Divide(Vector2 right) => this / right;
        [MethodImpl(AggressiveInlining)] public Vector2 Divide(Number scalar) => this / scalar;
        public Vector2 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        public Vector3 UnitSphere { [MethodImpl(AggressiveInlining)] get {
            var theta = this.X.Turns;
            var phi = this.Y.Multiply(((Number)0.5)).Turns;
            return (phi.Sin.Multiply(theta.Cos), phi.Sin.Multiply(theta.Sin), phi.Cos);
        }
         } 
public Vector3 Vector3 { [MethodImpl(AggressiveInlining)] get  => this.ToVector3(((Number)0)); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector3(Vector2 v) => v.Vector3;
        public Vector4 Vector4 { [MethodImpl(AggressiveInlining)] get  => this.ToVector4(((Number)0), ((Number)0)); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector4(Vector2 v) => v.Vector4;
        [MethodImpl(AggressiveInlining)] public Vector3 ToVector3(Number z) => (this.X, this.Y, z);
[MethodImpl(AggressiveInlining)] public Vector4 ToVector4(Number z, Number w) => (this.X, this.Y, z, w);
public static Vector2 UnitX { [MethodImpl(AggressiveInlining)] get  => (((Number)1), ((Number)0)); } 
public static Vector2 UnitY { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)1)); } 
[MethodImpl(AggressiveInlining)] public Number Cross(Vector2 b) => this.X.Multiply(b.Y).Subtract(this.Y.Multiply(b.X));
public Vector2 Perpendicular { [MethodImpl(AggressiveInlining)] get  => (this.Y.Negative, this.X); } 
[MethodImpl(AggressiveInlining)] public Vector2 Rotate(Angle a) => (this.X.Multiply(a.Cos).Subtract(this.Y.Multiply(a.Sin)), this.X.Multiply(a.Sin).Add(this.Y.Multiply(a.Cos)));
[MethodImpl(AggressiveInlining)] public Vector2 Project(Vector2 other) => other.Multiply(this.Dot(other));
[MethodImpl(AggressiveInlining)] public Angle Angle(Vector2 b) => this.Dot(b).Divide(this.Magnitude.Multiply(b.Magnitude)).Acos;
[MethodImpl(AggressiveInlining)] public Boolean IsParallel(Vector2 b) => this.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
public Vector2 PlusOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One); } 
public Vector2 MinusOne { [MethodImpl(AggressiveInlining)] get  => this.Subtract(One); } 
public Vector2 FromOne { [MethodImpl(AggressiveInlining)] get  => this.Negative.Add(One); } 
[MethodImpl(AggressiveInlining)] public Vector2 Barycentric(Vector2 v2, Vector2 v3, Vector2 uv) => this.Add(v2.Subtract(this).Multiply(uv.X)).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)] public Vector2 Linear(Vector2 b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Vector2 Quadratic(Vector2 b, Vector2 c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x)).Add(c);
[MethodImpl(AggressiveInlining)] public Vector2 Cubic(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(x.Pow3).Add(b.Multiply(x.Sqr)).Add(c.Multiply(x)).Add(d);
[MethodImpl(AggressiveInlining)] public Vector2 Quartic(Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => this.Multiply(x.Pow4).Add(b.Multiply(x.Pow3)).Add(c.Multiply(x.Sqr)).Add(d.Multiply(x)).Add(e);
[MethodImpl(AggressiveInlining)] public Vector2 LinearDerivative(Vector2 b, Number x) => this;
[MethodImpl(AggressiveInlining)] public Vector2 LinearSecondDerivative(Vector2 b, Number x) => default;
[MethodImpl(AggressiveInlining)] public Vector2 QuadraticDerivative(Vector2 b, Vector2 c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Vector2 QuadraticSecondDerivative(Vector2 b, Vector2 c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)] public Vector2 CubicDerivative(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x)).Add(c);
[MethodImpl(AggressiveInlining)] public Vector2 CubicSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)] public Vector2 QuarticDerivative(Vector2 b, Vector2 c, Vector2 d, Vector2 e, Vector2 x) => this.Multiply(((Number)4)).Multiply(x.Pow3).Add(b.Multiply(((Number)3)).Multiply(x.Sqr)).Add(c.Multiply(((Number)2)).Multiply(x)).Add(d);
[MethodImpl(AggressiveInlining)] public Vector2 QuarticSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x)).Add(c.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)] public Vector2 CubicBezier(Vector2 b, Vector2 c, Vector2 d, Number t) => this.Multiply(((Number)1).Subtract(t).Pow3).Add(b.Multiply(((Number)3)).Multiply(((Number)1).Subtract(t).Sqr).Multiply(t)).Add(c.Multiply(((Number)3)).Multiply(((Number)1).Subtract(t)).Multiply(t.Sqr)).Add(d.Multiply(t.Pow3));
[MethodImpl(AggressiveInlining)] public Vector2 CubicBezierDerivative(Vector2 b, Vector2 c, Vector2 d, Number t) => b.Subtract(this).Multiply(((Number)3)).Multiply(((Number)1).Subtract(t).Sqr).Add(c.Subtract(b).Multiply(((Number)6)).Multiply(((Number)1).Subtract(t)).Multiply(t)).Add(d.Subtract(c).Multiply(((Number)3)).Multiply(t.Sqr));
[MethodImpl(AggressiveInlining)] public Vector2 CubicBezierSecondDerivative(Vector2 b, Vector2 c, Vector2 d, Number t) => c.Subtract(b.Multiply(((Number)2))).Add(this).Multiply(((Number)6)).Multiply(((Number)1).Subtract(t)).Add(d.Subtract(c.Multiply(((Number)2))).Add(b).Multiply(((Number)6)).Multiply(t));
[MethodImpl(AggressiveInlining)] public Vector2 QuadraticBezier(Vector2 b, Vector2 c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2)).Multiply(((Number)1).Subtract(t)).Multiply(t)).Add(c.Multiply(t.Sqr));
[MethodImpl(AggressiveInlining)] public Vector2 QuadraticBezierDerivative(Vector2 b, Vector2 c, Number t) => b.Subtract(this).Multiply(((Number)2)).Multiply(((Number)1).Subtract(t)).Add(c.Subtract(b).Multiply(((Number)2)).Multiply(t));
[MethodImpl(AggressiveInlining)] public Vector2 QuadraticBezierSecondDerivative(Vector2 b, Vector2 c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2))).Add(c));
[MethodImpl(AggressiveInlining)] public Vector2 Hermite(Vector2 p1, Vector2 m0, Vector2 m1, Number t) => this.Multiply(((Number)2).Multiply(t.Pow3).Subtract(((Number)3).Multiply(t.Sqr)).Add(((Number)1))).Add(m0.Multiply(t.Pow3.Subtract(((Number)2).Multiply(t.Sqr)).Add(t))).Add(p1.Multiply(((Number)2).Negative.Multiply(t.Pow3).Add(((Number)3).Multiply(t.Sqr)))).Add(m1.Multiply(t.Pow3.Subtract(t.Sqr)));
[MethodImpl(AggressiveInlining)] public Vector2 HermiteDerivative(Vector2 p1, Vector2 m0, Vector2 m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t)).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Negative.Multiply(t.Sqr).Add(((Number)6).Multiply(t)))).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))));
[MethodImpl(AggressiveInlining)] public Vector2 CatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t)).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5))).Add(p2.Multiply(((Number)4))).Subtract(p3).Multiply(t.Sqr)).Add(this.Negative.Add(p1.Multiply(((Number)3))).Subtract(p2.Multiply(((Number)3))).Add(p3).Multiply(t.Pow3)));
[MethodImpl(AggressiveInlining)] public Vector2 CatmullRomDerivative(Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5))).Add(p2.Multiply(((Number)4))).Subtract(p3)).Multiply(t)).Add(((Number)3).Multiply(this.Negative.Add(p1.Multiply(((Number)3))).Subtract(p2.Multiply(((Number)3))).Add(p3)).Multiply(t.Sqr)));
public Vector2 SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Negative.Add(((Number)3))); } 
public Vector2 SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Pow3.Multiply(this.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10))); } 
public static Vector2 Zero { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(((Number)0)); } 
public static Vector2 One { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(((Number)1)); } 
public static Vector2 MinValue { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(Ara3D.Geometry.Number.MinValue); } 
public static Vector2 MaxValue { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponent(Ara3D.Geometry.Number.MaxValue); } 
[MethodImpl(AggressiveInlining)] public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Min(b)); } 
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Max(b)); } 
public Number SumComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSqrComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b.Multiply(b))); } 
public Number AvgComponent { [MethodImpl(AggressiveInlining)] get  => this.SumComponents.Divide(this.NumComponents); } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSqrComponents; } 
public Vector2 BitDecrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitDecrement); } 
public Vector2 BitIncrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitIncrement); } 
public Vector2 Cbrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Cbrt); } 
public Vector2 Ceiling { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Ceiling); } 
[MethodImpl(AggressiveInlining)] public Vector2 CopySign(Vector2 y) => this.ZipComponents(y, (a, b)  => a.CopySign(b));
public Vector2 Exp { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Exp); } 
public Vector2 Floor { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Floor); } 
[MethodImpl(AggressiveInlining)] public Vector2 FusedMultiplyAdd(Vector2 y, Vector2 z) => this.ZipComponents(y, z, (a, b, c)  => a.FusedMultiplyAdd(b, c));
public Vector2 ILogB { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ILogB); } 
[MethodImpl(AggressiveInlining)] public Vector2 IEEERemainder(Vector2 y) => this.ZipComponents(y, (a, b)  => a.IEEERemainder(b));
public Vector2 Log10 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log10); } 
public Vector2 Log2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log2); } 
[MethodImpl(AggressiveInlining)] public Vector2 MinMagnitude(Vector2 other) => this.ZipComponents(other, (a, b)  => a.MinMagnitude(b));
[MethodImpl(AggressiveInlining)] public Vector2 MaxMagnitude(Vector2 other) => this.ZipComponents(other, (a, b)  => a.MaxMagnitude(b));
public Vector2 NaturalLog { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.NaturalLog); } 
[MethodImpl(AggressiveInlining)] public Vector2 Pow(Vector2 power) => this.ZipComponents(power, (a, b)  => a.Pow(b));
public Vector2 Reciprocal { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Reciprocal); } 
public Vector2 ReciprocalEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalEstimate); } 
public Vector2 ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
[MethodImpl(AggressiveInlining)] public Vector2 RoundToZero(Integer digits){
            var _var94 = digits;
            return this.MapComponents((x)  => x.RoundToZero(_var94));
        }

[MethodImpl(AggressiveInlining)] public Vector2 ScaleB(Integer n){
            var _var95 = n;
            return this.MapComponents((x)  => x.ScaleB(_var95));
        }

[MethodImpl(AggressiveInlining)] public Boolean AlmostEqual(Vector2 y) => this.AllZipComponents(y, (a, b)  => a.AlmostEqual(b));
public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x)  => x.AlmostZero); } 
[MethodImpl(AggressiveInlining)] public Vector2 Average(Vector2 y) => this.Lerp(y, ((Number)0.5));
[MethodImpl(AggressiveInlining)] public Boolean Between(Vector2 a, Vector2 b) => this.AllZipComponents(a, b, (x1, a1, b1)  => x1.Between(a1, b1));
public Boolean Between01 { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x1)  => x1.Between01); } 
public Vector2 ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.ClampZeroOne); } 
public Vector2 Fract { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Fract); } 
[MethodImpl(AggressiveInlining)] public Vector2 InversePow(Vector2 y) => this.ZipComponents(y, (x1, y1)  => x1.InversePow(y1));
[MethodImpl(AggressiveInlining)] public Vector2 Lerp(Vector2 b, Number t){
            var _var96 = t;
            return this.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, _var96));
        }

[MethodImpl(AggressiveInlining)] public Vector2 MultiplyEpsilon(Vector2 y) => this.ZipComponents(y, (x1, y1)  => x1.MultiplyEpsilon(y1));
public Vector2 Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow2); } 
public Vector2 Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow3); } 
public Vector2 Pow4 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow4); } 
public Vector2 Pow5 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow5); } 
public Vector2 Sqr { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Sqr); } 
[MethodImpl(AggressiveInlining)] public IReadOnlyList<Vector2> Sample(Vector2 b, Integer n){
            var _var98 = b;
            {
                var _var97 = this;
                return n.LinearSpace.Map((i)  => _var97.Lerp(_var98, i));
            }
        }

public Vector2 Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Vector2 Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Vector2 Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Vector2 Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Vector2 Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Vector2 Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Vector2 Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Vector2 Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Vector2 Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Vector2 Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Vector2 Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Vector2 Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Vector2 Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Vector2 Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }
        public Vector2 Reverse { [MethodImpl(AggressiveInlining)] get  => Vector2.CreateFromComponents(this.Components.Reverse()); } 
[MethodImpl(AggressiveInlining)] public Vector2 MapComponents(System.Func<Number, Number> f) => Vector2.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)] public Vector2 ZipComponents(Vector2 b, System.Func<Number, Number, Number> f) => Vector2.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)] public Vector2 ZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Number> f) => Vector2.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Vector2 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Vector2 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)] public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Vector2 Modulo(Vector2 b) => this % b;
        [MethodImpl(AggressiveInlining)] public Vector2 Modulo(Number other) => this % other;
    }
    // Extension methods for the type
    public static class Vector2Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Vector2 Modulo(this Vector2 a, Vector2 b) => a.Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector2 Modulo(this System.Numerics.Vector2 a, Vector2 b) => ((Vector2)a).Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector2 Modulo(this Vector2 self, Number other) => self.Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Vector2 Modulo(this System.Numerics.Vector2 self, Number other) => ((Vector2)self).Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Point2D Point2D(this System.Numerics.Vector2 x) => ((Vector2)x).Point2D;
        [MethodImpl(AggressiveInlining)] public static Ray2D Ray2D(this System.Numerics.Vector2 v) => ((Vector2)v).Ray2D;
        [MethodImpl(AggressiveInlining)] public static Vector3 To3D(this System.Numerics.Vector2 x) => ((Vector2)x).To3D;
        [MethodImpl(AggressiveInlining)] public static Number X(this Vector2 self) => self.X;
        [MethodImpl(AggressiveInlining)] public static Number X(this System.Numerics.Vector2 self) => ((Vector2)self).X;
        [MethodImpl(AggressiveInlining)] public static Number Y(this Vector2 self) => self.Y;
        [MethodImpl(AggressiveInlining)] public static Number Y(this System.Numerics.Vector2 self) => ((Vector2)self).Y;
        [MethodImpl(AggressiveInlining)] public static Vector2 WithX(this Vector2 self, Number x) => self.WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector2 WithX(this System.Numerics.Vector2 self, Number x) => ((Vector2)self).WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector2 WithY(this Vector2 self, Number y) => self.WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 WithY(this System.Numerics.Vector2 self, Number y) => ((Vector2)self).WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 Normalize(this Vector2 self) => self.Normalize;
        [MethodImpl(AggressiveInlining)] public static Vector2 Normalize(this System.Numerics.Vector2 self) => ((Vector2)self).Normalize;
        [MethodImpl(AggressiveInlining)] public static Number Length(this Vector2 self) => self.Length;
        [MethodImpl(AggressiveInlining)] public static Number Length(this System.Numerics.Vector2 self) => ((Vector2)self).Length;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this Vector2 self) => self.LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this System.Numerics.Vector2 self) => ((Vector2)self).LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Vector2 Abs(this Vector2 self) => self.Abs;
        [MethodImpl(AggressiveInlining)] public static Vector2 Abs(this System.Numerics.Vector2 self) => ((Vector2)self).Abs;
        [MethodImpl(AggressiveInlining)] public static Vector2 Sqrt(this Vector2 self) => self.Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector2 Sqrt(this System.Numerics.Vector2 self) => ((Vector2)self).Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector2 Add(this Vector2 left, Vector2 right) => left.Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Add(this System.Numerics.Vector2 left, Vector2 right) => ((Vector2)left).Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Subtract(this Vector2 left, Vector2 right) => left.Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Subtract(this System.Numerics.Vector2 left, Vector2 right) => ((Vector2)left).Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this Vector2 left, Vector2 right) => left.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this System.Numerics.Vector2 left, Vector2 right) => ((Vector2)left).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this Vector2 left, Number scalar) => left.Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector2 Multiply(this System.Numerics.Vector2 left, Number scalar) => ((Vector2)left).Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector2 Divide(this Vector2 left, Vector2 right) => left.Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Divide(this System.Numerics.Vector2 left, Vector2 right) => ((Vector2)left).Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector2 Divide(this Vector2 left, Number scalar) => left.Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector2 Divide(this System.Numerics.Vector2 left, Number scalar) => ((Vector2)left).Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector2 Negative(this Vector2 value) => value.Negative;
        [MethodImpl(AggressiveInlining)] public static Vector2 Negative(this System.Numerics.Vector2 value) => ((Vector2)value).Negative;
        [MethodImpl(AggressiveInlining)] public static Number Dot(this Vector2 self, Vector2 right) => self.Dot(right);
        [MethodImpl(AggressiveInlining)] public static Number Dot(this System.Numerics.Vector2 self, Vector2 right) => ((Vector2)self).Dot(right);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this Vector2 self, Vector2 value2) => self.Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this System.Numerics.Vector2 self, Vector2 value2) => ((Vector2)self).Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this Vector2 self, Vector2 value2) => self.DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this System.Numerics.Vector2 self, Vector2 value2) => ((Vector2)self).DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Vector2 Clamp(this Vector2 self, Vector2 min, Vector2 max) => self.Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector2 Clamp(this System.Numerics.Vector2 self, Vector2 min, Vector2 max) => ((Vector2)self).Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector2 Reflect(this Vector2 self, Vector2 normal) => self.Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector2 Reflect(this System.Numerics.Vector2 self, Vector2 normal) => ((Vector2)self).Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this Vector2 self, Matrix3x2 matrix) => self.Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this System.Numerics.Vector2 self, Matrix3x2 matrix) => ((Vector2)self).Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this Vector2 self, Matrix4x4 matrix) => self.Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this System.Numerics.Vector2 self, Matrix4x4 matrix) => ((Vector2)self).Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this Vector2 self, Quaternion rotation) => self.Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector2 Transform(this System.Numerics.Vector2 self, Quaternion rotation) => ((Vector2)self).Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector2 TransformNormal(this Vector2 self, Matrix3x2 matrix) => self.TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 TransformNormal(this System.Numerics.Vector2 self, Matrix3x2 matrix) => ((Vector2)self).TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 TransformNormal(this Vector2 self, Matrix4x4 matrix) => self.TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 TransformNormal(this System.Numerics.Vector2 self, Matrix4x4 matrix) => ((Vector2)self).TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector2 Max(this Vector2 self, Vector2 value2) => self.Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector2 Max(this System.Numerics.Vector2 self, Vector2 value2) => ((Vector2)self).Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector2 Min(this Vector2 self, Vector2 value2) => self.Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector2 Min(this System.Numerics.Vector2 self, Vector2 value2) => ((Vector2)self).Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 UnitSphere(this System.Numerics.Vector2 uv) => ((Vector2)uv).UnitSphere;
        [MethodImpl(AggressiveInlining)] public static Vector3 Vector3(this System.Numerics.Vector2 v) => ((Vector2)v).Vector3;
        [MethodImpl(AggressiveInlining)] public static Vector4 Vector4(this System.Numerics.Vector2 v) => ((Vector2)v).Vector4;
        [MethodImpl(AggressiveInlining)] public static Vector3 ToVector3(this System.Numerics.Vector2 v, Number z) => ((Vector2)v).ToVector3(z);
        [MethodImpl(AggressiveInlining)] public static Vector4 ToVector4(this System.Numerics.Vector2 v, Number z, Number w) => ((Vector2)v).ToVector4(z, w);
        [MethodImpl(AggressiveInlining)] public static Number Cross(this System.Numerics.Vector2 a, Vector2 b) => ((Vector2)a).Cross(b);
        [MethodImpl(AggressiveInlining)] public static Vector2 Perpendicular(this System.Numerics.Vector2 v) => ((Vector2)v).Perpendicular;
        [MethodImpl(AggressiveInlining)] public static Vector2 Rotate(this System.Numerics.Vector2 v, Angle a) => ((Vector2)v).Rotate(a);
        [MethodImpl(AggressiveInlining)] public static Vector2 Project(this System.Numerics.Vector2 v, Vector2 other) => ((Vector2)v).Project(other);
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this System.Numerics.Vector2 a, Vector2 b) => ((Vector2)a).Angle(b);
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this System.Numerics.Vector2 a, Vector2 b) => ((Vector2)a).IsParallel(b);
        [MethodImpl(AggressiveInlining)] public static Vector2 PlusOne(this System.Numerics.Vector2 x) => ((Vector2)x).PlusOne;
        [MethodImpl(AggressiveInlining)] public static Vector2 MinusOne(this System.Numerics.Vector2 x) => ((Vector2)x).MinusOne;
        [MethodImpl(AggressiveInlining)] public static Vector2 FromOne(this System.Numerics.Vector2 x) => ((Vector2)x).FromOne;
        [MethodImpl(AggressiveInlining)] public static Vector2 Barycentric(this System.Numerics.Vector2 v1, Vector2 v2, Vector2 v3, Vector2 uv) => ((Vector2)v1).Barycentric(v2, v3, uv);
        [MethodImpl(AggressiveInlining)] public static Vector2 Linear(this System.Numerics.Vector2 m, Vector2 b, Number x) => ((Vector2)m).Linear(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 Quadratic(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number x) => ((Vector2)a).Quadratic(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 Cubic(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number x) => ((Vector2)a).Cubic(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 Quartic(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => ((Vector2)a).Quartic(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 LinearDerivative(this System.Numerics.Vector2 m, Vector2 b, Number x) => ((Vector2)m).LinearDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 LinearSecondDerivative(this System.Numerics.Vector2 m, Vector2 b, Number x) => ((Vector2)m).LinearSecondDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuadraticDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number x) => ((Vector2)a).QuadraticDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuadraticSecondDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number x) => ((Vector2)a).QuadraticSecondDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 CubicDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number x) => ((Vector2)a).CubicDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 CubicSecondDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number x) => ((Vector2)a).CubicSecondDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuarticDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Vector2 e, Vector2 x) => ((Vector2)a).QuarticDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuarticSecondDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Vector2 e, Number x) => ((Vector2)a).QuarticSecondDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector2 CubicBezier(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number t) => ((Vector2)a).CubicBezier(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 CubicBezierDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number t) => ((Vector2)a).CubicBezierDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 CubicBezierSecondDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Vector2 d, Number t) => ((Vector2)a).CubicBezierSecondDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuadraticBezier(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number t) => ((Vector2)a).QuadraticBezier(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuadraticBezierDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number t) => ((Vector2)a).QuadraticBezierDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 QuadraticBezierSecondDerivative(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, Number t) => ((Vector2)a).QuadraticBezierSecondDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 Hermite(this System.Numerics.Vector2 p0, Vector2 p1, Vector2 m0, Vector2 m1, Number t) => ((Vector2)p0).Hermite(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 HermiteDerivative(this System.Numerics.Vector2 p0, Vector2 p1, Vector2 m0, Vector2 m1, Number t) => ((Vector2)p0).HermiteDerivative(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 CatmullRom(this System.Numerics.Vector2 p0, Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Vector2)p0).CatmullRom(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 CatmullRomDerivative(this System.Numerics.Vector2 p0, Vector2 p1, Vector2 p2, Vector2 p3, Number t) => ((Vector2)p0).CatmullRomDerivative(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 SmoothStep(this System.Numerics.Vector2 x) => ((Vector2)x).SmoothStep;
        [MethodImpl(AggressiveInlining)] public static Vector2 SmootherStep(this System.Numerics.Vector2 x) => ((Vector2)x).SmootherStep;
        [MethodImpl(AggressiveInlining)] public static Number Reduce(this System.Numerics.Vector2 v, Number initial, System.Func<Number, Number, Number> f) => ((Vector2)v).Reduce(initial, f);
        [MethodImpl(AggressiveInlining)] public static Number MinComponent(this System.Numerics.Vector2 x) => ((Vector2)x).MinComponent;
        [MethodImpl(AggressiveInlining)] public static Number MaxComponent(this System.Numerics.Vector2 x) => ((Vector2)x).MaxComponent;
        [MethodImpl(AggressiveInlining)] public static Number SumComponents(this System.Numerics.Vector2 v) => ((Vector2)v).SumComponents;
        [MethodImpl(AggressiveInlining)] public static Number SumSqrComponents(this System.Numerics.Vector2 v) => ((Vector2)v).SumSqrComponents;
        [MethodImpl(AggressiveInlining)] public static Number AvgComponent(this System.Numerics.Vector2 v) => ((Vector2)v).AvgComponent;
        [MethodImpl(AggressiveInlining)] public static Number Magnitude(this System.Numerics.Vector2 v) => ((Vector2)v).Magnitude;
        [MethodImpl(AggressiveInlining)] public static Number MagnitudeSquared(this System.Numerics.Vector2 v) => ((Vector2)v).MagnitudeSquared;
        [MethodImpl(AggressiveInlining)] public static Vector2 BitDecrement(this System.Numerics.Vector2 self) => ((Vector2)self).BitDecrement;
        [MethodImpl(AggressiveInlining)] public static Vector2 BitIncrement(this System.Numerics.Vector2 self) => ((Vector2)self).BitIncrement;
        [MethodImpl(AggressiveInlining)] public static Vector2 Cbrt(this System.Numerics.Vector2 self) => ((Vector2)self).Cbrt;
        [MethodImpl(AggressiveInlining)] public static Vector2 Ceiling(this System.Numerics.Vector2 self) => ((Vector2)self).Ceiling;
        [MethodImpl(AggressiveInlining)] public static Vector2 CopySign(this System.Numerics.Vector2 self, Vector2 y) => ((Vector2)self).CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 Exp(this System.Numerics.Vector2 self) => ((Vector2)self).Exp;
        [MethodImpl(AggressiveInlining)] public static Vector2 Floor(this System.Numerics.Vector2 self) => ((Vector2)self).Floor;
        [MethodImpl(AggressiveInlining)] public static Vector2 FusedMultiplyAdd(this System.Numerics.Vector2 self, Vector2 y, Vector2 z) => ((Vector2)self).FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Vector2 ILogB(this System.Numerics.Vector2 self) => ((Vector2)self).ILogB;
        [MethodImpl(AggressiveInlining)] public static Vector2 IEEERemainder(this System.Numerics.Vector2 self, Vector2 y) => ((Vector2)self).IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 Log10(this System.Numerics.Vector2 self) => ((Vector2)self).Log10;
        [MethodImpl(AggressiveInlining)] public static Vector2 Log2(this System.Numerics.Vector2 self) => ((Vector2)self).Log2;
        [MethodImpl(AggressiveInlining)] public static Vector2 MinMagnitude(this System.Numerics.Vector2 self, Vector2 other) => ((Vector2)self).MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector2 MaxMagnitude(this System.Numerics.Vector2 self, Vector2 other) => ((Vector2)self).MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector2 NaturalLog(this System.Numerics.Vector2 self) => ((Vector2)self).NaturalLog;
        [MethodImpl(AggressiveInlining)] public static Vector2 Pow(this System.Numerics.Vector2 self, Vector2 power) => ((Vector2)self).Pow(power);
        [MethodImpl(AggressiveInlining)] public static Vector2 Reciprocal(this System.Numerics.Vector2 self) => ((Vector2)self).Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Vector2 ReciprocalEstimate(this System.Numerics.Vector2 self) => ((Vector2)self).ReciprocalEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector2 ReciprocalSquareRootEstimate(this System.Numerics.Vector2 self) => ((Vector2)self).ReciprocalSquareRootEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector2 RoundToZero(this System.Numerics.Vector2 self, Integer digits) => ((Vector2)self).RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Vector2 ScaleB(this System.Numerics.Vector2 self, Integer n) => ((Vector2)self).ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostEqual(this System.Numerics.Vector2 x, Vector2 y) => ((Vector2)x).AlmostEqual(y);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostZero(this System.Numerics.Vector2 x) => ((Vector2)x).AlmostZero;
        [MethodImpl(AggressiveInlining)] public static Vector2 Average(this System.Numerics.Vector2 x, Vector2 y) => ((Vector2)x).Average(y);
        [MethodImpl(AggressiveInlining)] public static Boolean Between(this System.Numerics.Vector2 x, Vector2 a, Vector2 b) => ((Vector2)x).Between(a, b);
        [MethodImpl(AggressiveInlining)] public static Boolean Between01(this System.Numerics.Vector2 x) => ((Vector2)x).Between01;
        [MethodImpl(AggressiveInlining)] public static Vector2 ClampZeroOne(this System.Numerics.Vector2 x) => ((Vector2)x).ClampZeroOne;
        [MethodImpl(AggressiveInlining)] public static Vector2 Fract(this System.Numerics.Vector2 x) => ((Vector2)x).Fract;
        [MethodImpl(AggressiveInlining)] public static Vector2 InversePow(this System.Numerics.Vector2 x, Vector2 y) => ((Vector2)x).InversePow(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 Lerp(this System.Numerics.Vector2 a, Vector2 b, Number t) => ((Vector2)a).Lerp(b, t);
        [MethodImpl(AggressiveInlining)] public static Vector2 MultiplyEpsilon(this System.Numerics.Vector2 x, Vector2 y) => ((Vector2)x).MultiplyEpsilon(y);
        [MethodImpl(AggressiveInlining)] public static Vector2 Pow2(this System.Numerics.Vector2 x) => ((Vector2)x).Pow2;
        [MethodImpl(AggressiveInlining)] public static Vector2 Pow3(this System.Numerics.Vector2 x) => ((Vector2)x).Pow3;
        [MethodImpl(AggressiveInlining)] public static Vector2 Pow4(this System.Numerics.Vector2 x) => ((Vector2)x).Pow4;
        [MethodImpl(AggressiveInlining)] public static Vector2 Pow5(this System.Numerics.Vector2 x) => ((Vector2)x).Pow5;
        [MethodImpl(AggressiveInlining)] public static Vector2 Sqr(this System.Numerics.Vector2 x) => ((Vector2)x).Sqr;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Vector2> Sample(this System.Numerics.Vector2 a, Vector2 b, Integer n) => ((Vector2)a).Sample(b, n);
        [MethodImpl(AggressiveInlining)] public static Vector2 Half(this System.Numerics.Vector2 x) => ((Vector2)x).Half;
        [MethodImpl(AggressiveInlining)] public static Vector2 Quarter(this System.Numerics.Vector2 x) => ((Vector2)x).Quarter;
        [MethodImpl(AggressiveInlining)] public static Vector2 Eight(this System.Numerics.Vector2 x) => ((Vector2)x).Eight;
        [MethodImpl(AggressiveInlining)] public static Vector2 Sixteenth(this System.Numerics.Vector2 x) => ((Vector2)x).Sixteenth;
        [MethodImpl(AggressiveInlining)] public static Vector2 Tenth(this System.Numerics.Vector2 x) => ((Vector2)x).Tenth;
        [MethodImpl(AggressiveInlining)] public static Vector2 Twice(this System.Numerics.Vector2 x) => ((Vector2)x).Twice;
        [MethodImpl(AggressiveInlining)] public static Vector2 Hundred(this System.Numerics.Vector2 x) => ((Vector2)x).Hundred;
        [MethodImpl(AggressiveInlining)] public static Vector2 Thousand(this System.Numerics.Vector2 x) => ((Vector2)x).Thousand;
        [MethodImpl(AggressiveInlining)] public static Vector2 Million(this System.Numerics.Vector2 x) => ((Vector2)x).Million;
        [MethodImpl(AggressiveInlining)] public static Vector2 Billion(this System.Numerics.Vector2 x) => ((Vector2)x).Billion;
        [MethodImpl(AggressiveInlining)] public static Vector2 Hundredth(this System.Numerics.Vector2 x) => ((Vector2)x).Hundredth;
        [MethodImpl(AggressiveInlining)] public static Vector2 Thousandth(this System.Numerics.Vector2 x) => ((Vector2)x).Thousandth;
        [MethodImpl(AggressiveInlining)] public static Vector2 Millionth(this System.Numerics.Vector2 x) => ((Vector2)x).Millionth;
        [MethodImpl(AggressiveInlining)] public static Vector2 Billionth(this System.Numerics.Vector2 x) => ((Vector2)x).Billionth;
        [MethodImpl(AggressiveInlining)] public static Number At(this System.Numerics.Vector2 xs, Integer n) => ((Vector2)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Vector2 Reverse(this System.Numerics.Vector2 xs) => ((Vector2)xs).Reverse;
        [MethodImpl(AggressiveInlining)] public static Vector2 MapComponents(this System.Numerics.Vector2 x, System.Func<Number, Number> f) => ((Vector2)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Vector2 ZipComponents(this System.Numerics.Vector2 a, Vector2 b, System.Func<Number, Number, Number> f) => ((Vector2)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Vector2 ZipComponents(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, System.Func<Number, Number, Number, Number> f) => ((Vector2)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector2 a, Vector2 b, System.Func<Number, Number, Boolean> f) => ((Vector2)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector2)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector2 a, Vector2 b, System.Func<Number, Number, Boolean> f) => ((Vector2)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector2 a, Vector2 b, Vector2 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector2)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllComponents(this System.Numerics.Vector2 x, System.Func<Number, Boolean> predicate) => ((Vector2)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyComponent(this System.Numerics.Vector2 x, System.Func<Number, Boolean> predicate) => ((Vector2)x).AnyComponent(predicate);
    }
}
