// Autogenerated file: DO NOT EDIT
// Created on 2026-07-10 11:44:52 AM

using System.Runtime.CompilerServices;
using System.Runtime.Serialization;
using System.Runtime.InteropServices;
using static System.Runtime.CompilerServices.MethodImplOptions;
using Ara3D.Collections;

namespace Ara3D.Geometry
{
    [StructLayout(LayoutKind.Sequential, Pack=1)]
    public partial struct Vector3: IVector<Vector3>
    {
        // Static factory function
        [MethodImpl(AggressiveInlining)] public static Vector3 Create(Number x, Number y, Number z) => new Vector3(x, y, z);

        // Static default implementation
        public static readonly Vector3 Default = default;

        // Implicit converters to/from value-tuples and deconstructor
        [MethodImpl(AggressiveInlining)] public static implicit operator (Number, Number, Number)(Vector3 self) => (self.X, self.Y, self.Z);
        [MethodImpl(AggressiveInlining)] public static implicit operator Vector3((Number, Number, Number) value) => new Vector3(value.Item1, value.Item2, value.Item3);
        [MethodImpl(AggressiveInlining)] public void Deconstruct(out Number x, out Number y, out Number z) { x = X; y = Y; z = Z;  }

        // Object virtual function overrides: Equals, GetHashCode, ToString
        [MethodImpl(AggressiveInlining)] public Boolean Equals(Vector3 other) => Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public Boolean NotEquals(Vector3 other) => !Value.Equals(other.Value);
        [MethodImpl(AggressiveInlining)] public override bool Equals(object obj) => obj is Vector3 other ? Equals(other) : false;
        [MethodImpl(AggressiveInlining)] public static Boolean operator==(Vector3 a, Vector3 b) => a.Equals(b);
        [MethodImpl(AggressiveInlining)] public static Boolean operator!=(Vector3 a, Vector3 b) => !a.Equals(b);
        [MethodImpl(AggressiveInlining)] public override int GetHashCode() => Value.GetHashCode();
        [MethodImpl(AggressiveInlining)] public override string ToString() => Value.ToString();

        // Explicit implementation of interfaces by forwarding properties to fields

        // IArrayLike predefined functions
        public Integer NumComponents { [MethodImpl(AggressiveInlining)] get => 3; }
        public IReadOnlyList<Number> Components { [MethodImpl(AggressiveInlining)] get => Intrinsics.MakeArray<Number>(X, Y, Z); }
        [MethodImpl(AggressiveInlining)] public static Vector3 CreateFromComponents(IReadOnlyList<Number> numbers) => new Vector3(numbers[0], numbers[1], numbers[2]);

        [MethodImpl(AggressiveInlining)] public static Vector3 CreateFromComponent(Number x) => new Vector3(x, x, x);

        // Implemented interface functions
        public Point3D Point3D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y, this.Z); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Point3D(Vector3 x) => x.Point3D;
        public Ray3D Ray3D { [MethodImpl(AggressiveInlining)] get  => (Constants.Origin3D, this); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Ray3D(Vector3 v) => v.Ray3D;
        [MethodImpl(AggressiveInlining)] public Vector3 Add(Vector3 right) => this + right;
        [MethodImpl(AggressiveInlining)] public Vector3 Subtract(Vector3 right) => this - right;
        [MethodImpl(AggressiveInlining)] public Vector3 Multiply(Vector3 right) => this * right;
        [MethodImpl(AggressiveInlining)] public Vector3 Multiply(Number scalar) => this * scalar;
        [MethodImpl(AggressiveInlining)] public Vector3 Divide(Vector3 right) => this / right;
        [MethodImpl(AggressiveInlining)] public Vector3 Divide(Number scalar) => this / scalar;
        public Vector3 Negative { [MethodImpl(AggressiveInlining)] get => -this; }
        [MethodImpl(AggressiveInlining)] public Number SdSphere(Number r) => this.Length.Subtract(r);
[MethodImpl(AggressiveInlining)] public Number SdBox(Vector3 b){
            var q = this.Abs.Subtract(b);
            return q.Max(((Number)0).Vector3).Length.Add(q.X.Max(q.Y.Max(q.Z)).Min(((Number)0)));
        }

[MethodImpl(AggressiveInlining)] public Number SdRoundBox(Vector3 b, Number r){
            var q = this.Abs.Subtract(b).Add(r.Vector3);
            return q.Max(((Number)0).Vector3).Length.Add(q.X.Max(q.Y.Max(q.Z)).Min(((Number)0))).Subtract(r);
        }

[MethodImpl(AggressiveInlining)] public Number SdTorus(Vector2 t){
            var q = new Vector2(this.XZ.Length.Subtract(t.X), this.Y);
            return q.Length.Subtract(t.Y);
        }

[MethodImpl(AggressiveInlining)] public Number SdVerticalCapsule(Number h, Number r){
            var py = this.Y.Subtract(this.Y.Clamp(((Number)0), h));
            return new Vector3(this.X, py, this.Z).Length.Subtract(r);
        }

[MethodImpl(AggressiveInlining)] public Number SdCappedCylinder(Number h, Number r){
            var d = new Vector2(this.XZ.Length, this.Y).Abs.Subtract(new Vector2(r, h));
            return d.X.Max(d.Y).Min(((Number)0)).Add(d.Max(((Number)0).Vector2).Length);
        }

[MethodImpl(AggressiveInlining)] public Number SdPlane(Vector3 n, Number h) => this.Dot(n).Add(h);
[MethodImpl(AggressiveInlining)] public AxisAngle Rotation(Angle a) => (this, a);
public Vector4 Vector4 { [MethodImpl(AggressiveInlining)] get  => this.ToVector4(((Number)0)); } 
[MethodImpl(AggressiveInlining)]  public static implicit operator Vector4(Vector3 v) => v.Vector4;
        [MethodImpl(AggressiveInlining)] public Vector4 ToVector4(Number w) => (this.X, this.Y, this.Z, w);
public Vector3 XZY { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Z, this.Y); } 
public Vector3 YXZ { [MethodImpl(AggressiveInlining)] get  => (this.Y, this.X, this.Z); } 
public Vector3 YZX { [MethodImpl(AggressiveInlining)] get  => (this.Y, this.Z, this.X); } 
public Vector3 ZXY { [MethodImpl(AggressiveInlining)] get  => (this.Z, this.X, this.Y); } 
public Vector3 ZYX { [MethodImpl(AggressiveInlining)] get  => (this.Z, this.Y, this.X); } 
public Vector2 XY { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y); } 
public Vector2 YX { [MethodImpl(AggressiveInlining)] get  => (this.Y, this.X); } 
public Vector2 XZ { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Z); } 
public Vector2 ZX { [MethodImpl(AggressiveInlining)] get  => (this.Z, this.X); } 
public Vector2 YZ { [MethodImpl(AggressiveInlining)] get  => (this.Y, this.Z); } 
public Vector2 ZY { [MethodImpl(AggressiveInlining)] get  => (this.Z, this.Y); } 
public Vector2 XX { [MethodImpl(AggressiveInlining)] get  => (this.X, this.X); } 
public Vector2 YY { [MethodImpl(AggressiveInlining)] get  => (this.Y, this.Y); } 
public Vector2 ZZ { [MethodImpl(AggressiveInlining)] get  => (this.Z, this.Z); } 
[MethodImpl(AggressiveInlining)] public Vector3 Project(Plane p) => this.Subtract(p.Normal.Multiply(p.Normal.Dot(this)));
[MethodImpl(AggressiveInlining)] public Number MixedProduct(Vector3 b, Vector3 c) => this.Cross(b).Dot(c);
public Vector2 To2D { [MethodImpl(AggressiveInlining)] get  => (this.X, this.Y); } 
public static Vector3 UnitX { [MethodImpl(AggressiveInlining)] get  => (((Number)1), ((Number)0), ((Number)0)); } 
public static Vector3 UnitY { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)1), ((Number)0)); } 
public static Vector3 UnitZ { [MethodImpl(AggressiveInlining)] get  => (((Number)0), ((Number)0), ((Number)1)); } 
[MethodImpl(AggressiveInlining)] public Vector3 Project(Vector3 other) => other.Multiply(this.Dot(other));
[MethodImpl(AggressiveInlining)] public Angle Angle(Vector3 b) => this.Dot(b).Divide(this.Magnitude.Multiply(b.Magnitude)).Acos;
[MethodImpl(AggressiveInlining)] public Boolean IsParallel(Vector3 b) => this.Dot(b).Abs.GreaterThanOrEquals(((Number)1).Subtract(Constants.Epsilon));
public Vector3 PlusOne { [MethodImpl(AggressiveInlining)] get  => this.Add(One); } 
public Vector3 MinusOne { [MethodImpl(AggressiveInlining)] get  => this.Subtract(One); } 
public Vector3 FromOne { [MethodImpl(AggressiveInlining)] get  => this.Negative.Add(One); } 
[MethodImpl(AggressiveInlining)] public Vector3 Barycentric(Vector3 v2, Vector3 v3, Vector2 uv) => this.Add(v2.Subtract(this).Multiply(uv.X)).Add(v3.Subtract(this).Multiply(uv.Y));
[MethodImpl(AggressiveInlining)] public Vector3 Linear(Vector3 b, Number x) => this.Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Vector3 Quadratic(Vector3 b, Vector3 c, Number x) => this.Multiply(x.Sqr).Add(b.Multiply(x)).Add(c);
[MethodImpl(AggressiveInlining)] public Vector3 Cubic(Vector3 b, Vector3 c, Vector3 d, Number x) => this.Multiply(x.Pow3).Add(b.Multiply(x.Sqr)).Add(c.Multiply(x)).Add(d);
[MethodImpl(AggressiveInlining)] public Vector3 Quartic(Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => this.Multiply(x.Pow4).Add(b.Multiply(x.Pow3)).Add(c.Multiply(x.Sqr)).Add(d.Multiply(x)).Add(e);
[MethodImpl(AggressiveInlining)] public Vector3 LinearDerivative(Vector3 b, Number x) => this;
[MethodImpl(AggressiveInlining)] public Vector3 LinearSecondDerivative(Vector3 b, Number x) => default;
[MethodImpl(AggressiveInlining)] public Vector3 QuadraticDerivative(Vector3 b, Vector3 c, Number x) => this.Multiply(((Number)2)).Multiply(x).Add(b);
[MethodImpl(AggressiveInlining)] public Vector3 QuadraticSecondDerivative(Vector3 b, Vector3 c, Number x) => this.Multiply(((Number)2));
[MethodImpl(AggressiveInlining)] public Vector3 CubicDerivative(Vector3 b, Vector3 c, Vector3 d, Number x) => this.Multiply(((Number)3)).Multiply(x.Sqr).Add(b.Multiply(((Number)2)).Multiply(x)).Add(c);
[MethodImpl(AggressiveInlining)] public Vector3 CubicSecondDerivative(Vector3 b, Vector3 c, Vector3 d, Number x) => this.Multiply(((Number)6)).Multiply(x).Add(b.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)] public Vector3 QuarticDerivative(Vector3 b, Vector3 c, Vector3 d, Vector3 e, Vector3 x) => this.Multiply(((Number)4)).Multiply(x.Pow3).Add(b.Multiply(((Number)3)).Multiply(x.Sqr)).Add(c.Multiply(((Number)2)).Multiply(x)).Add(d);
[MethodImpl(AggressiveInlining)] public Vector3 QuarticSecondDerivative(Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => this.Multiply(((Number)12)).Multiply(x.Sqr).Add(b.Multiply(((Number)6)).Multiply(x)).Add(c.Multiply(((Number)2)));
[MethodImpl(AggressiveInlining)] public Vector3 CubicBezier(Vector3 b, Vector3 c, Vector3 d, Number t) => this.Multiply(((Number)1).Subtract(t).Pow3).Add(b.Multiply(((Number)3)).Multiply(((Number)1).Subtract(t).Sqr).Multiply(t)).Add(c.Multiply(((Number)3)).Multiply(((Number)1).Subtract(t)).Multiply(t.Sqr)).Add(d.Multiply(t.Pow3));
[MethodImpl(AggressiveInlining)] public Vector3 CubicBezierDerivative(Vector3 b, Vector3 c, Vector3 d, Number t) => b.Subtract(this).Multiply(((Number)3)).Multiply(((Number)1).Subtract(t).Sqr).Add(c.Subtract(b).Multiply(((Number)6)).Multiply(((Number)1).Subtract(t)).Multiply(t)).Add(d.Subtract(c).Multiply(((Number)3)).Multiply(t.Sqr));
[MethodImpl(AggressiveInlining)] public Vector3 CubicBezierSecondDerivative(Vector3 b, Vector3 c, Vector3 d, Number t) => c.Subtract(b.Multiply(((Number)2))).Add(this).Multiply(((Number)6)).Multiply(((Number)1).Subtract(t)).Add(d.Subtract(c.Multiply(((Number)2))).Add(b).Multiply(((Number)6)).Multiply(t));
[MethodImpl(AggressiveInlining)] public Vector3 QuadraticBezier(Vector3 b, Vector3 c, Number t) => this.Multiply(((Number)1).Subtract(t).Sqr).Add(b.Multiply(((Number)2)).Multiply(((Number)1).Subtract(t)).Multiply(t)).Add(c.Multiply(t.Sqr));
[MethodImpl(AggressiveInlining)] public Vector3 QuadraticBezierDerivative(Vector3 b, Vector3 c, Number t) => b.Subtract(this).Multiply(((Number)2)).Multiply(((Number)1).Subtract(t)).Add(c.Subtract(b).Multiply(((Number)2)).Multiply(t));
[MethodImpl(AggressiveInlining)] public Vector3 QuadraticBezierSecondDerivative(Vector3 b, Vector3 c, Number t) => ((Number)2).Multiply(this.Subtract(b.Multiply(((Number)2))).Add(c));
[MethodImpl(AggressiveInlining)] public Vector3 Hermite(Vector3 p1, Vector3 m0, Vector3 m1, Number t) => this.Multiply(((Number)2).Multiply(t.Pow3).Subtract(((Number)3).Multiply(t.Sqr)).Add(((Number)1))).Add(m0.Multiply(t.Pow3.Subtract(((Number)2).Multiply(t.Sqr)).Add(t))).Add(p1.Multiply(((Number)2).Negative.Multiply(t.Pow3).Add(((Number)3).Multiply(t.Sqr)))).Add(m1.Multiply(t.Pow3.Subtract(t.Sqr)));
[MethodImpl(AggressiveInlining)] public Vector3 HermiteDerivative(Vector3 p1, Vector3 m0, Vector3 m1, Number t) => this.Multiply(((Number)6).Multiply(t.Sqr).Subtract(((Number)6).Multiply(t))).Add(m0.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)4).Multiply(t)).Add(((Number)1)))).Add(p1.Multiply(((Number)6).Negative.Multiply(t.Sqr).Add(((Number)6).Multiply(t)))).Add(m1.Multiply(((Number)3).Multiply(t.Sqr).Subtract(((Number)2).Multiply(t))));
[MethodImpl(AggressiveInlining)] public Vector3 CatmullRom(Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Number)0.5).Multiply(p1.Multiply(((Number)2)).Add(p2.Subtract(this).Multiply(t)).Add(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5))).Add(p2.Multiply(((Number)4))).Subtract(p3).Multiply(t.Sqr)).Add(this.Negative.Add(p1.Multiply(((Number)3))).Subtract(p2.Multiply(((Number)3))).Add(p3).Multiply(t.Pow3)));
[MethodImpl(AggressiveInlining)] public Vector3 CatmullRomDerivative(Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Number)0.5).Multiply(p2.Subtract(this).Add(((Number)2).Multiply(this.Multiply(((Number)2)).Subtract(p1.Multiply(((Number)5))).Add(p2.Multiply(((Number)4))).Subtract(p3)).Multiply(t)).Add(((Number)3).Multiply(this.Negative.Add(p1.Multiply(((Number)3))).Subtract(p2.Multiply(((Number)3))).Add(p3)).Multiply(t.Sqr)));
public Vector3 SmoothStep { [MethodImpl(AggressiveInlining)] get  => this.Sqr.Multiply(this.Twice.Negative.Add(((Number)3))); } 
public Vector3 SmootherStep { [MethodImpl(AggressiveInlining)] get  => this.Pow3.Multiply(this.Multiply(this.Multiply(((Number)6)).Subtract(((Number)15))).Add(((Number)10))); } 
public static Vector3 Zero { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(((Number)0)); } 
public static Vector3 One { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(((Number)1)); } 
public static Vector3 MinValue { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(Ara3D.Geometry.Number.MinValue); } 
public static Vector3 MaxValue { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponent(Ara3D.Geometry.Number.MaxValue); } 
[MethodImpl(AggressiveInlining)] public Number Reduce(Number initial, System.Func<Number, Number, Number> f) => this.Components.Reduce(initial, f);
public Number MinComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Min(b)); } 
public Number MaxComponent { [MethodImpl(AggressiveInlining)] get  => this.Reduce(this[((Integer)0)], (a, b)  => a.Max(b)); } 
public Number SumComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b)); } 
public Number SumSqrComponents { [MethodImpl(AggressiveInlining)] get  => this.Reduce(((Number)0), (a, b)  => a.Add(b.Multiply(b))); } 
public Number AvgComponent { [MethodImpl(AggressiveInlining)] get  => this.SumComponents.Divide(this.NumComponents); } 
public Number Magnitude { [MethodImpl(AggressiveInlining)] get  => this.MagnitudeSquared.Sqrt; } 
public Number MagnitudeSquared { [MethodImpl(AggressiveInlining)] get  => this.SumSqrComponents; } 
public Vector3 BitDecrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitDecrement); } 
public Vector3 BitIncrement { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.BitIncrement); } 
public Vector3 Cbrt { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Cbrt); } 
public Vector3 Ceiling { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Ceiling); } 
[MethodImpl(AggressiveInlining)] public Vector3 CopySign(Vector3 y) => this.ZipComponents(y, (a, b)  => a.CopySign(b));
public Vector3 Exp { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Exp); } 
public Vector3 Floor { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Floor); } 
[MethodImpl(AggressiveInlining)] public Vector3 FusedMultiplyAdd(Vector3 y, Vector3 z) => this.ZipComponents(y, z, (a, b, c)  => a.FusedMultiplyAdd(b, c));
public Vector3 ILogB { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ILogB); } 
[MethodImpl(AggressiveInlining)] public Vector3 IEEERemainder(Vector3 y) => this.ZipComponents(y, (a, b)  => a.IEEERemainder(b));
public Vector3 Log10 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log10); } 
public Vector3 Log2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Log2); } 
[MethodImpl(AggressiveInlining)] public Vector3 MinMagnitude(Vector3 other) => this.ZipComponents(other, (a, b)  => a.MinMagnitude(b));
[MethodImpl(AggressiveInlining)] public Vector3 MaxMagnitude(Vector3 other) => this.ZipComponents(other, (a, b)  => a.MaxMagnitude(b));
public Vector3 NaturalLog { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.NaturalLog); } 
[MethodImpl(AggressiveInlining)] public Vector3 Pow(Vector3 power) => this.ZipComponents(power, (a, b)  => a.Pow(b));
public Vector3 Reciprocal { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.Reciprocal); } 
public Vector3 ReciprocalEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalEstimate); } 
public Vector3 ReciprocalSquareRootEstimate { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x)  => x.ReciprocalSquareRootEstimate); } 
[MethodImpl(AggressiveInlining)] public Vector3 RoundToZero(Integer digits){
            var _var99 = digits;
            return this.MapComponents((x)  => x.RoundToZero(_var99));
        }

[MethodImpl(AggressiveInlining)] public Vector3 ScaleB(Integer n){
            var _var100 = n;
            return this.MapComponents((x)  => x.ScaleB(_var100));
        }

[MethodImpl(AggressiveInlining)] public Boolean AlmostEqual(Vector3 y) => this.AllZipComponents(y, (a, b)  => a.AlmostEqual(b));
public Boolean AlmostZero { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x)  => x.AlmostZero); } 
[MethodImpl(AggressiveInlining)] public Vector3 Average(Vector3 y) => this.Lerp(y, ((Number)0.5));
[MethodImpl(AggressiveInlining)] public Boolean Between(Vector3 a, Vector3 b) => this.AllZipComponents(a, b, (x1, a1, b1)  => x1.Between(a1, b1));
public Boolean Between01 { [MethodImpl(AggressiveInlining)] get  => this.AllComponents((x1)  => x1.Between01); } 
public Vector3 ClampZeroOne { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.ClampZeroOne); } 
public Vector3 Fract { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Fract); } 
[MethodImpl(AggressiveInlining)] public Vector3 InversePow(Vector3 y) => this.ZipComponents(y, (x1, y1)  => x1.InversePow(y1));
[MethodImpl(AggressiveInlining)] public Vector3 Lerp(Vector3 b, Number t){
            var _var101 = t;
            return this.ZipComponents(b, (a1, b1)  => a1.Lerp(b1, _var101));
        }

[MethodImpl(AggressiveInlining)] public Vector3 MultiplyEpsilon(Vector3 y) => this.ZipComponents(y, (x1, y1)  => x1.MultiplyEpsilon(y1));
public Vector3 Pow2 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow2); } 
public Vector3 Pow3 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow3); } 
public Vector3 Pow4 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow4); } 
public Vector3 Pow5 { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Pow5); } 
public Vector3 Sqr { [MethodImpl(AggressiveInlining)] get  => this.MapComponents((x1)  => x1.Sqr); } 
[MethodImpl(AggressiveInlining)] public IReadOnlyList<Vector3> Sample(Vector3 b, Integer n){
            var _var103 = b;
            {
                var _var102 = this;
                return n.LinearSpace.Map((i)  => _var102.Lerp(_var103, i));
            }
        }

public Vector3 Half { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)2)); } 
public Vector3 Quarter { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)4)); } 
public Vector3 Eight { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)8)); } 
public Vector3 Sixteenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)16)); } 
public Vector3 Tenth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)10)); } 
public Vector3 Twice { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)2)); } 
public Vector3 Hundred { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)100)); } 
public Vector3 Thousand { [MethodImpl(AggressiveInlining)] get  => this.Multiply(((Number)1000)); } 
public Vector3 Million { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Thousand; } 
public Vector3 Billion { [MethodImpl(AggressiveInlining)] get  => this.Thousand.Million; } 
public Vector3 Hundredth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)100)); } 
public Vector3 Thousandth { [MethodImpl(AggressiveInlining)] get  => this.Divide(((Number)1000)); } 
public Vector3 Millionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Thousandth; } 
public Vector3 Billionth { [MethodImpl(AggressiveInlining)] get  => this.Thousandth.Millionth; } 
[MethodImpl(AggressiveInlining)] public Number At(Integer n) => this.Components[n];
public Number this[Integer n] { [MethodImpl(AggressiveInlining)]  get => At(n); }
        public Vector3 Reverse { [MethodImpl(AggressiveInlining)] get  => Vector3.CreateFromComponents(this.Components.Reverse()); } 
[MethodImpl(AggressiveInlining)] public Vector3 MapComponents(System.Func<Number, Number> f) => Vector3.CreateFromComponents(this.Components.Map(f));
[MethodImpl(AggressiveInlining)] public Vector3 ZipComponents(Vector3 b, System.Func<Number, Number, Number> f) => Vector3.CreateFromComponents(this.Components.Zip(b.Components, f));
[MethodImpl(AggressiveInlining)] public Vector3 ZipComponents(Vector3 b, Vector3 c, System.Func<Number, Number, Number, Number> f) => Vector3.CreateFromComponents(this.Components.Zip(b.Components, c.Components, f));
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Vector3 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllZipComponents(Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).All((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Vector3 b, System.Func<Number, Number, Boolean> f) => this.Components.Zip(b.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AnyZipComponents(Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => this.Components.Zip(b.Components, c.Components, f).Any((x)  => x);
[MethodImpl(AggressiveInlining)] public Boolean AllComponents(System.Func<Number, Boolean> predicate) => this.Components.All(predicate);
[MethodImpl(AggressiveInlining)] public Boolean AnyComponent(System.Func<Number, Boolean> predicate) => this.Components.Any(predicate);

        // Unimplemented interface functions
        [MethodImpl(AggressiveInlining)] public Vector3 Modulo(Vector3 b) => this % b;
        [MethodImpl(AggressiveInlining)] public Vector3 Modulo(Number other) => this % other;
    }
    // Extension methods for the type
    public static class Vector3Extensions
    {
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this Vector3 a, Vector3 b) => a.Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).Modulo(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this Vector3 self, Number other) => self.Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 Modulo(this System.Numerics.Vector3 self, Number other) => ((Vector3)self).Modulo(other);
        [MethodImpl(AggressiveInlining)] public static Point3D Point3D(this System.Numerics.Vector3 x) => ((Vector3)x).Point3D;
        [MethodImpl(AggressiveInlining)] public static Ray3D Ray3D(this System.Numerics.Vector3 v) => ((Vector3)v).Ray3D;
        [MethodImpl(AggressiveInlining)] public static Number X(this Vector3 self) => self.X;
        [MethodImpl(AggressiveInlining)] public static Number X(this System.Numerics.Vector3 self) => ((Vector3)self).X;
        [MethodImpl(AggressiveInlining)] public static Number Y(this Vector3 self) => self.Y;
        [MethodImpl(AggressiveInlining)] public static Number Y(this System.Numerics.Vector3 self) => ((Vector3)self).Y;
        [MethodImpl(AggressiveInlining)] public static Number Z(this Vector3 self) => self.Z;
        [MethodImpl(AggressiveInlining)] public static Number Z(this System.Numerics.Vector3 self) => ((Vector3)self).Z;
        [MethodImpl(AggressiveInlining)] public static Vector3 WithX(this Vector3 self, Number x) => self.WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithX(this System.Numerics.Vector3 self, Number x) => ((Vector3)self).WithX(x);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithY(this Vector3 self, Number y) => self.WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithY(this System.Numerics.Vector3 self, Number y) => ((Vector3)self).WithY(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithZ(this Vector3 self, Number z) => self.WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector3 WithZ(this System.Numerics.Vector3 self, Number z) => ((Vector3)self).WithZ(z);
        [MethodImpl(AggressiveInlining)] public static Vector3 Normalize(this Vector3 self) => self.Normalize;
        [MethodImpl(AggressiveInlining)] public static Vector3 Normalize(this System.Numerics.Vector3 self) => ((Vector3)self).Normalize;
        [MethodImpl(AggressiveInlining)] public static Number Length(this Vector3 self) => self.Length;
        [MethodImpl(AggressiveInlining)] public static Number Length(this System.Numerics.Vector3 self) => ((Vector3)self).Length;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this Vector3 self) => self.LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Number LengthSquared(this System.Numerics.Vector3 self) => ((Vector3)self).LengthSquared;
        [MethodImpl(AggressiveInlining)] public static Vector3 Abs(this Vector3 self) => self.Abs;
        [MethodImpl(AggressiveInlining)] public static Vector3 Abs(this System.Numerics.Vector3 self) => ((Vector3)self).Abs;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqrt(this Vector3 self) => self.Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqrt(this System.Numerics.Vector3 self) => ((Vector3)self).Sqrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Add(this Vector3 left, Vector3 right) => left.Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Add(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Add(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Subtract(this Vector3 left, Vector3 right) => left.Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Subtract(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Subtract(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this Vector3 left, Vector3 right) => left.Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Multiply(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this Vector3 left, Number scalar) => left.Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Multiply(this System.Numerics.Vector3 left, Number scalar) => ((Vector3)left).Multiply(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this Vector3 left, Vector3 right) => left.Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this System.Numerics.Vector3 left, Vector3 right) => ((Vector3)left).Divide(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this Vector3 left, Number scalar) => left.Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Divide(this System.Numerics.Vector3 left, Number scalar) => ((Vector3)left).Divide(scalar);
        [MethodImpl(AggressiveInlining)] public static Vector3 Negative(this Vector3 value) => value.Negative;
        [MethodImpl(AggressiveInlining)] public static Vector3 Negative(this System.Numerics.Vector3 value) => ((Vector3)value).Negative;
        [MethodImpl(AggressiveInlining)] public static Number Dot(this Vector3 self, Vector3 right) => self.Dot(right);
        [MethodImpl(AggressiveInlining)] public static Number Dot(this System.Numerics.Vector3 self, Vector3 right) => ((Vector3)self).Dot(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cross(this Vector3 self, Vector3 right) => self.Cross(right);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cross(this System.Numerics.Vector3 self, Vector3 right) => ((Vector3)self).Cross(right);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this Vector3 self, Vector3 value2) => self.Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number Distance(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Distance(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this Vector3 self, Vector3 value2) => self.DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Number DistanceSquared(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).DistanceSquared(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Clamp(this Vector3 self, Vector3 min, Vector3 max) => self.Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector3 Clamp(this System.Numerics.Vector3 self, Vector3 min, Vector3 max) => ((Vector3)self).Clamp(min, max);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reflect(this Vector3 self, Vector3 normal) => self.Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reflect(this System.Numerics.Vector3 self, Vector3 normal) => ((Vector3)self).Reflect(normal);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Vector3 self, Matrix4x4 matrix) => self.Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this System.Numerics.Vector3 self, Matrix4x4 matrix) => ((Vector3)self).Transform(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this Vector3 self, Quaternion rotation) => self.Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector3 Transform(this System.Numerics.Vector3 self, Quaternion rotation) => ((Vector3)self).Transform(rotation);
        [MethodImpl(AggressiveInlining)] public static Vector3 TransformNormal(this Vector3 self, Matrix4x4 matrix) => self.TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 TransformNormal(this System.Numerics.Vector3 self, Matrix4x4 matrix) => ((Vector3)self).TransformNormal(matrix);
        [MethodImpl(AggressiveInlining)] public static Vector3 Max(this Vector3 self, Vector3 value2) => self.Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Max(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Max(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Min(this Vector3 self, Vector3 value2) => self.Min(value2);
        [MethodImpl(AggressiveInlining)] public static Vector3 Min(this System.Numerics.Vector3 self, Vector3 value2) => ((Vector3)self).Min(value2);
        [MethodImpl(AggressiveInlining)] public static Number SdSphere(this System.Numerics.Vector3 p, Number r) => ((Vector3)p).SdSphere(r);
        [MethodImpl(AggressiveInlining)] public static Number SdBox(this System.Numerics.Vector3 p, Vector3 b) => ((Vector3)p).SdBox(b);
        [MethodImpl(AggressiveInlining)] public static Number SdRoundBox(this System.Numerics.Vector3 p, Vector3 b, Number r) => ((Vector3)p).SdRoundBox(b, r);
        [MethodImpl(AggressiveInlining)] public static Number SdTorus(this System.Numerics.Vector3 p, Vector2 t) => ((Vector3)p).SdTorus(t);
        [MethodImpl(AggressiveInlining)] public static Number SdVerticalCapsule(this System.Numerics.Vector3 p, Number h, Number r) => ((Vector3)p).SdVerticalCapsule(h, r);
        [MethodImpl(AggressiveInlining)] public static Number SdCappedCylinder(this System.Numerics.Vector3 p, Number h, Number r) => ((Vector3)p).SdCappedCylinder(h, r);
        [MethodImpl(AggressiveInlining)] public static Number SdPlane(this System.Numerics.Vector3 p, Vector3 n, Number h) => ((Vector3)p).SdPlane(n, h);
        [MethodImpl(AggressiveInlining)] public static AxisAngle Rotation(this System.Numerics.Vector3 axis, Angle a) => ((Vector3)axis).Rotation(a);
        [MethodImpl(AggressiveInlining)] public static Vector4 Vector4(this System.Numerics.Vector3 v) => ((Vector3)v).Vector4;
        [MethodImpl(AggressiveInlining)] public static Vector4 ToVector4(this System.Numerics.Vector3 v, Number w) => ((Vector3)v).ToVector4(w);
        [MethodImpl(AggressiveInlining)] public static Vector3 XZY(this System.Numerics.Vector3 v) => ((Vector3)v).XZY;
        [MethodImpl(AggressiveInlining)] public static Vector3 YXZ(this System.Numerics.Vector3 v) => ((Vector3)v).YXZ;
        [MethodImpl(AggressiveInlining)] public static Vector3 YZX(this System.Numerics.Vector3 v) => ((Vector3)v).YZX;
        [MethodImpl(AggressiveInlining)] public static Vector3 ZXY(this System.Numerics.Vector3 v) => ((Vector3)v).ZXY;
        [MethodImpl(AggressiveInlining)] public static Vector3 ZYX(this System.Numerics.Vector3 v) => ((Vector3)v).ZYX;
        [MethodImpl(AggressiveInlining)] public static Vector2 XY(this System.Numerics.Vector3 v) => ((Vector3)v).XY;
        [MethodImpl(AggressiveInlining)] public static Vector2 YX(this System.Numerics.Vector3 v) => ((Vector3)v).YX;
        [MethodImpl(AggressiveInlining)] public static Vector2 XZ(this System.Numerics.Vector3 v) => ((Vector3)v).XZ;
        [MethodImpl(AggressiveInlining)] public static Vector2 ZX(this System.Numerics.Vector3 v) => ((Vector3)v).ZX;
        [MethodImpl(AggressiveInlining)] public static Vector2 YZ(this System.Numerics.Vector3 v) => ((Vector3)v).YZ;
        [MethodImpl(AggressiveInlining)] public static Vector2 ZY(this System.Numerics.Vector3 v) => ((Vector3)v).ZY;
        [MethodImpl(AggressiveInlining)] public static Vector2 XX(this System.Numerics.Vector3 v) => ((Vector3)v).XX;
        [MethodImpl(AggressiveInlining)] public static Vector2 YY(this System.Numerics.Vector3 v) => ((Vector3)v).YY;
        [MethodImpl(AggressiveInlining)] public static Vector2 ZZ(this System.Numerics.Vector3 v) => ((Vector3)v).ZZ;
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this System.Numerics.Vector3 v, Plane p) => ((Vector3)v).Project(p);
        [MethodImpl(AggressiveInlining)] public static Number MixedProduct(this System.Numerics.Vector3 a, Vector3 b, Vector3 c) => ((Vector3)a).MixedProduct(b, c);
        [MethodImpl(AggressiveInlining)] public static Vector2 To2D(this System.Numerics.Vector3 v) => ((Vector3)v).To2D;
        [MethodImpl(AggressiveInlining)] public static Vector3 Project(this System.Numerics.Vector3 v, Vector3 other) => ((Vector3)v).Project(other);
        [MethodImpl(AggressiveInlining)] public static Angle Angle(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).Angle(b);
        [MethodImpl(AggressiveInlining)] public static Boolean IsParallel(this System.Numerics.Vector3 a, Vector3 b) => ((Vector3)a).IsParallel(b);
        [MethodImpl(AggressiveInlining)] public static Vector3 PlusOne(this System.Numerics.Vector3 x) => ((Vector3)x).PlusOne;
        [MethodImpl(AggressiveInlining)] public static Vector3 MinusOne(this System.Numerics.Vector3 x) => ((Vector3)x).MinusOne;
        [MethodImpl(AggressiveInlining)] public static Vector3 FromOne(this System.Numerics.Vector3 x) => ((Vector3)x).FromOne;
        [MethodImpl(AggressiveInlining)] public static Vector3 Barycentric(this System.Numerics.Vector3 v1, Vector3 v2, Vector3 v3, Vector2 uv) => ((Vector3)v1).Barycentric(v2, v3, uv);
        [MethodImpl(AggressiveInlining)] public static Vector3 Linear(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).Linear(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Quadratic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).Quadratic(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Cubic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).Cubic(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 Quartic(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => ((Vector3)a).Quartic(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 LinearDerivative(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).LinearDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 LinearSecondDerivative(this System.Numerics.Vector3 m, Vector3 b, Number x) => ((Vector3)m).LinearSecondDerivative(b, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).QuadraticDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number x) => ((Vector3)a).QuadraticSecondDerivative(b, c, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).CubicDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number x) => ((Vector3)a).CubicSecondDerivative(b, c, d, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuarticDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Vector3 x) => ((Vector3)a).QuarticDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuarticSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Vector3 e, Number x) => ((Vector3)a).QuarticSecondDerivative(b, c, d, e, x);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezier(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezier(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezierDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezierDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CubicBezierSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Vector3 d, Number t) => ((Vector3)a).CubicBezierSecondDerivative(b, c, d, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezier(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezier(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezierDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezierDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 QuadraticBezierSecondDerivative(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, Number t) => ((Vector3)a).QuadraticBezierSecondDerivative(b, c, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 Hermite(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 m0, Vector3 m1, Number t) => ((Vector3)p0).Hermite(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 HermiteDerivative(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 m0, Vector3 m1, Number t) => ((Vector3)p0).HermiteDerivative(p1, m0, m1, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CatmullRom(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Vector3)p0).CatmullRom(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 CatmullRomDerivative(this System.Numerics.Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, Number t) => ((Vector3)p0).CatmullRomDerivative(p1, p2, p3, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 SmoothStep(this System.Numerics.Vector3 x) => ((Vector3)x).SmoothStep;
        [MethodImpl(AggressiveInlining)] public static Vector3 SmootherStep(this System.Numerics.Vector3 x) => ((Vector3)x).SmootherStep;
        [MethodImpl(AggressiveInlining)] public static Number Reduce(this System.Numerics.Vector3 v, Number initial, System.Func<Number, Number, Number> f) => ((Vector3)v).Reduce(initial, f);
        [MethodImpl(AggressiveInlining)] public static Number MinComponent(this System.Numerics.Vector3 x) => ((Vector3)x).MinComponent;
        [MethodImpl(AggressiveInlining)] public static Number MaxComponent(this System.Numerics.Vector3 x) => ((Vector3)x).MaxComponent;
        [MethodImpl(AggressiveInlining)] public static Number SumComponents(this System.Numerics.Vector3 v) => ((Vector3)v).SumComponents;
        [MethodImpl(AggressiveInlining)] public static Number SumSqrComponents(this System.Numerics.Vector3 v) => ((Vector3)v).SumSqrComponents;
        [MethodImpl(AggressiveInlining)] public static Number AvgComponent(this System.Numerics.Vector3 v) => ((Vector3)v).AvgComponent;
        [MethodImpl(AggressiveInlining)] public static Number Magnitude(this System.Numerics.Vector3 v) => ((Vector3)v).Magnitude;
        [MethodImpl(AggressiveInlining)] public static Number MagnitudeSquared(this System.Numerics.Vector3 v) => ((Vector3)v).MagnitudeSquared;
        [MethodImpl(AggressiveInlining)] public static Vector3 BitDecrement(this System.Numerics.Vector3 self) => ((Vector3)self).BitDecrement;
        [MethodImpl(AggressiveInlining)] public static Vector3 BitIncrement(this System.Numerics.Vector3 self) => ((Vector3)self).BitIncrement;
        [MethodImpl(AggressiveInlining)] public static Vector3 Cbrt(this System.Numerics.Vector3 self) => ((Vector3)self).Cbrt;
        [MethodImpl(AggressiveInlining)] public static Vector3 Ceiling(this System.Numerics.Vector3 self) => ((Vector3)self).Ceiling;
        [MethodImpl(AggressiveInlining)] public static Vector3 CopySign(this System.Numerics.Vector3 self, Vector3 y) => ((Vector3)self).CopySign(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Exp(this System.Numerics.Vector3 self) => ((Vector3)self).Exp;
        [MethodImpl(AggressiveInlining)] public static Vector3 Floor(this System.Numerics.Vector3 self) => ((Vector3)self).Floor;
        [MethodImpl(AggressiveInlining)] public static Vector3 FusedMultiplyAdd(this System.Numerics.Vector3 self, Vector3 y, Vector3 z) => ((Vector3)self).FusedMultiplyAdd(y, z);
        [MethodImpl(AggressiveInlining)] public static Vector3 ILogB(this System.Numerics.Vector3 self) => ((Vector3)self).ILogB;
        [MethodImpl(AggressiveInlining)] public static Vector3 IEEERemainder(this System.Numerics.Vector3 self, Vector3 y) => ((Vector3)self).IEEERemainder(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Log10(this System.Numerics.Vector3 self) => ((Vector3)self).Log10;
        [MethodImpl(AggressiveInlining)] public static Vector3 Log2(this System.Numerics.Vector3 self) => ((Vector3)self).Log2;
        [MethodImpl(AggressiveInlining)] public static Vector3 MinMagnitude(this System.Numerics.Vector3 self, Vector3 other) => ((Vector3)self).MinMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 MaxMagnitude(this System.Numerics.Vector3 self, Vector3 other) => ((Vector3)self).MaxMagnitude(other);
        [MethodImpl(AggressiveInlining)] public static Vector3 NaturalLog(this System.Numerics.Vector3 self) => ((Vector3)self).NaturalLog;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow(this System.Numerics.Vector3 self, Vector3 power) => ((Vector3)self).Pow(power);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reciprocal(this System.Numerics.Vector3 self) => ((Vector3)self).Reciprocal;
        [MethodImpl(AggressiveInlining)] public static Vector3 ReciprocalEstimate(this System.Numerics.Vector3 self) => ((Vector3)self).ReciprocalEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector3 ReciprocalSquareRootEstimate(this System.Numerics.Vector3 self) => ((Vector3)self).ReciprocalSquareRootEstimate;
        [MethodImpl(AggressiveInlining)] public static Vector3 RoundToZero(this System.Numerics.Vector3 self, Integer digits) => ((Vector3)self).RoundToZero(digits);
        [MethodImpl(AggressiveInlining)] public static Vector3 ScaleB(this System.Numerics.Vector3 self, Integer n) => ((Vector3)self).ScaleB(n);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostEqual(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).AlmostEqual(y);
        [MethodImpl(AggressiveInlining)] public static Boolean AlmostZero(this System.Numerics.Vector3 x) => ((Vector3)x).AlmostZero;
        [MethodImpl(AggressiveInlining)] public static Vector3 Average(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).Average(y);
        [MethodImpl(AggressiveInlining)] public static Boolean Between(this System.Numerics.Vector3 x, Vector3 a, Vector3 b) => ((Vector3)x).Between(a, b);
        [MethodImpl(AggressiveInlining)] public static Boolean Between01(this System.Numerics.Vector3 x) => ((Vector3)x).Between01;
        [MethodImpl(AggressiveInlining)] public static Vector3 ClampZeroOne(this System.Numerics.Vector3 x) => ((Vector3)x).ClampZeroOne;
        [MethodImpl(AggressiveInlining)] public static Vector3 Fract(this System.Numerics.Vector3 x) => ((Vector3)x).Fract;
        [MethodImpl(AggressiveInlining)] public static Vector3 InversePow(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).InversePow(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Lerp(this System.Numerics.Vector3 a, Vector3 b, Number t) => ((Vector3)a).Lerp(b, t);
        [MethodImpl(AggressiveInlining)] public static Vector3 MultiplyEpsilon(this System.Numerics.Vector3 x, Vector3 y) => ((Vector3)x).MultiplyEpsilon(y);
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow2(this System.Numerics.Vector3 x) => ((Vector3)x).Pow2;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow3(this System.Numerics.Vector3 x) => ((Vector3)x).Pow3;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow4(this System.Numerics.Vector3 x) => ((Vector3)x).Pow4;
        [MethodImpl(AggressiveInlining)] public static Vector3 Pow5(this System.Numerics.Vector3 x) => ((Vector3)x).Pow5;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sqr(this System.Numerics.Vector3 x) => ((Vector3)x).Sqr;
        [MethodImpl(AggressiveInlining)] public static IReadOnlyList<Vector3> Sample(this System.Numerics.Vector3 a, Vector3 b, Integer n) => ((Vector3)a).Sample(b, n);
        [MethodImpl(AggressiveInlining)] public static Vector3 Half(this System.Numerics.Vector3 x) => ((Vector3)x).Half;
        [MethodImpl(AggressiveInlining)] public static Vector3 Quarter(this System.Numerics.Vector3 x) => ((Vector3)x).Quarter;
        [MethodImpl(AggressiveInlining)] public static Vector3 Eight(this System.Numerics.Vector3 x) => ((Vector3)x).Eight;
        [MethodImpl(AggressiveInlining)] public static Vector3 Sixteenth(this System.Numerics.Vector3 x) => ((Vector3)x).Sixteenth;
        [MethodImpl(AggressiveInlining)] public static Vector3 Tenth(this System.Numerics.Vector3 x) => ((Vector3)x).Tenth;
        [MethodImpl(AggressiveInlining)] public static Vector3 Twice(this System.Numerics.Vector3 x) => ((Vector3)x).Twice;
        [MethodImpl(AggressiveInlining)] public static Vector3 Hundred(this System.Numerics.Vector3 x) => ((Vector3)x).Hundred;
        [MethodImpl(AggressiveInlining)] public static Vector3 Thousand(this System.Numerics.Vector3 x) => ((Vector3)x).Thousand;
        [MethodImpl(AggressiveInlining)] public static Vector3 Million(this System.Numerics.Vector3 x) => ((Vector3)x).Million;
        [MethodImpl(AggressiveInlining)] public static Vector3 Billion(this System.Numerics.Vector3 x) => ((Vector3)x).Billion;
        [MethodImpl(AggressiveInlining)] public static Vector3 Hundredth(this System.Numerics.Vector3 x) => ((Vector3)x).Hundredth;
        [MethodImpl(AggressiveInlining)] public static Vector3 Thousandth(this System.Numerics.Vector3 x) => ((Vector3)x).Thousandth;
        [MethodImpl(AggressiveInlining)] public static Vector3 Millionth(this System.Numerics.Vector3 x) => ((Vector3)x).Millionth;
        [MethodImpl(AggressiveInlining)] public static Vector3 Billionth(this System.Numerics.Vector3 x) => ((Vector3)x).Billionth;
        [MethodImpl(AggressiveInlining)] public static Number At(this System.Numerics.Vector3 xs, Integer n) => ((Vector3)xs).At(n);
        [MethodImpl(AggressiveInlining)] public static Vector3 Reverse(this System.Numerics.Vector3 xs) => ((Vector3)xs).Reverse;
        [MethodImpl(AggressiveInlining)] public static Vector3 MapComponents(this System.Numerics.Vector3 x, System.Func<Number, Number> f) => ((Vector3)x).MapComponents(f);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Number> f) => ((Vector3)a).ZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Vector3 ZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Number> f) => ((Vector3)a).ZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Boolean> f) => ((Vector3)a).AllZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector3)a).AllZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector3 a, Vector3 b, System.Func<Number, Number, Boolean> f) => ((Vector3)a).AnyZipComponents(b, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyZipComponents(this System.Numerics.Vector3 a, Vector3 b, Vector3 c, System.Func<Number, Number, Number, Boolean> f) => ((Vector3)a).AnyZipComponents(b, c, f);
        [MethodImpl(AggressiveInlining)] public static Boolean AllComponents(this System.Numerics.Vector3 x, System.Func<Number, Boolean> predicate) => ((Vector3)x).AllComponents(predicate);
        [MethodImpl(AggressiveInlining)] public static Boolean AnyComponent(this System.Numerics.Vector3 x, System.Func<Number, Boolean> predicate) => ((Vector3)x).AnyComponent(predicate);
    }
}
