<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Builders, accessors, and a navigable object model over BIM Open Schema data.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.Collections" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.DataTable" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.Geometry" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.Models" Version="$(Ara3DSdkVersion)" />
    <PackageReference Include="Ara3D.Utils" Version="$(Ara3DSdkVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\submodules\bim-open-schema\src\Ara3D.BimOpenSchema\Ara3D.BimOpenSchema.csproj" />
  </ItemGroup>

</Project>
