<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(Ara3DMicrosoftNetTestSdkVersion)" />
    <PackageReference Include="NUnit" Version="$(Ara3DNUnitVersion)" />
    <PackageReference Include="NUnit3TestAdapter" Version="$(Ara3DNUnit3TestAdapterVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.Utils" Version="$(Ara3DSdkVersion)" />
    <ProjectReference Include="..\..\submodules\parakeet\Parakeet\Ara3D.Parakeet.csproj" />
    <ProjectReference Include="..\..\submodules\parakeet\Parakeet.Grammars\Ara3D.Parakeet.Grammars.csproj" />
    <ProjectReference Include="..\..\submodules\parakeet\Parakeet.Tests\Ara3D.Parakeet.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
