// Codegen for contracts/contracts.json -> C# and TypeScript.
// Usage: node contracts/generate.mjs   (from the repo root or anywhere)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const idl = JSON.parse(readFileSync(join(root, "contracts.json"), "utf8"));

const upper = (s) => s[0].toUpperCase() + s.slice(1);

// --- field type mapping ---------------------------------------------------
const parseType = (t) => {
  const optional = t.endsWith("?");
  const base = optional ? t.slice(0, -1) : t;
  const arrays = (base.match(/\[\]/g) ?? []).length;
  return { core: base.replace(/\[\]/g, ""), arrays, optional };
};

const csType = (t) => {
  const { core, arrays, optional } = parseType(t);
  const map = { string: "string", int: "int", number: "double", bool: "bool", any: "object" };
  let cs = map[core] ?? core;
  for (let i = 0; i < arrays; i++) cs = `IReadOnlyList<${cs}>`;
  return optional ? `${cs}?` : cs;
};

const tsType = (t) => {
  const { core, arrays, optional } = parseType(t);
  const map = { string: "string", int: "number", number: "number", bool: "boolean", any: "unknown" };
  let ts = map[core] ?? core;
  for (let i = 0; i < arrays; i++) ts = `${ts}[]`;
  return optional ? `${ts} | undefined` : ts;
};

// --- C# -------------------------------------------------------------------
let cs = `// <auto-generated>
// Generated from contracts/contracts.json v${idl.version} by contracts/generate.mjs.
// Do not edit by hand.
// </auto-generated>
using System.Collections.Generic;

namespace BimOpenFlow.Contracts;

`;
for (const [name, values] of Object.entries(idl.enums))
  cs += `public enum ${name}\n{\n${values.map((v) => `    ${v},`).join("\n")}\n}\n\n`;
for (const [name, fields] of Object.entries(idl.types)) {
  const args = Object.entries(fields)
    .map(([f, t]) => `    ${csType(t)} ${upper(f)}${t.endsWith("?") ? " = null" : ""}`)
    .join(",\n");
  cs += `public sealed record ${name}(\n${args});\n\n`;
}

// --- TypeScript -----------------------------------------------------------
let ts = `// Generated from contracts/contracts.json v${idl.version} by contracts/generate.mjs.
// Do not edit by hand.

`;
for (const [name, values] of Object.entries(idl.enums))
  ts += `export type ${name} =\n${values.map((v) => `  | "${v}"`).join("\n")};\n\n`;
for (const [name, fields] of Object.entries(idl.types)) {
  const body = Object.entries(fields)
    .map(([f, t]) => `  ${f}${t.endsWith("?") ? "?" : ""}: ${tsType(t)};`)
    .join("\n");
  ts += `export interface ${name} {\n${body}\n}\n\n`;
}

// --- emit -----------------------------------------------------------------
const emit = (path, content) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log("wrote", path);
};
emit(join(root, "generated", "csharp", "BimOpenFlow.Contracts.g.cs"), cs);
emit(join(root, "..", "bimopenflow", "web", "packages", "contracts", "src", "index.ts"), ts);
