<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Ara3D.Ifc.Mesher</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Description>WIP library comparing two pure C# IFC meshing approaches.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ara3D.IfcLoader\Ara3D.IfcLoader.csproj" />
    <ProjectReference Include="..\Ara3D.Geometry\Ara3D.Geometry.csproj" />
    <ProjectReference Include="..\Ara3D.IO.StepParser\Ara3D.IO.StepParser.csproj" />
    <ProjectReference Include="..\Ara3D.Memory\Ara3D.Memory.csproj" />
    <ProjectReference Include="..\Ara3D.Models\Ara3D.Models.csproj" />
    <ProjectReference Include="..\Ara3D.Utils\Ara3D.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Ara3D.IfcLoader" />
    <Using Include="Ara3D.IfcTypes" />
    <Using Include="Ara3D.IfcTypes.Ifc4" />
  </ItemGroup>

</Project>
